import json
import os

candidates = [
    {
        "id": "c_01",
        "name": "Aditya Khamitkar",
        "title": "Junior Data Scientist & AI Engineer",
        "experience_years": 2,
        "location": "Pune, India",
        "education": "B.Tech Computer Science",
        "notice_period": "Immediate",
        "salary_expectation": "12 LPA",
        "preferred_work_mode": "Hybrid",
        "current_job_satisfaction": "Moderate",
        "summary": "Passionate Junior Data Scientist focusing on advanced LLM architectures.",
        "skills": ["Deep Learning", "LLM Architectures", "Python", "PyTorch", "Transformers", "NLP"],
        "past_roles": [],
        "certifications": []
    },
    {
        "id": "c_02",
        "name": "Rukesh Reddy",
        "title": "Founder & CEO",
        "experience_years": 16,
        "location": "Hyderabad, India",
        "education": "IIT Bombay, IIM Ahmedabad",
        "notice_period": "N/A",
        "salary_expectation": "N/A - Equity driven",
        "preferred_work_mode": "Hybrid",
        "current_job_satisfaction": "Extremely high - building my own company",
        "summary": "15+ yrs leadership experience at Citi, Monitor, and JP Morgan. Currently leading Deccan AI.",
        "skills": ["Leadership", "Strategy", "Finance", "AI Strategy", "Enterprise Architecture"],
        "past_roles": [{"role": "Vice President", "company": "JP Morgan", "duration": "5 years", "highlights": ["Led global AI strategy"]}],
        "certifications": []
    },
    {
        "id": "c_03",
        "name": "Jagdeep Sahni",
        "title": "VP of New Accounts",
        "experience_years": 12,
        "location": "Remote",
        "education": "MBA",
        "notice_period": "30 days",
        "salary_expectation": "45 LPA",
        "preferred_work_mode": "Remote",
        "current_job_satisfaction": "High",
        "summary": "Driving growth and new account acquisition for AI solutions.",
        "skills": ["Sales", "Account Management", "B2B Sales", "AI Solutions Strategy"],
        "past_roles": [],
        "certifications": []
    },
    {
        "id": "c_04",
        "name": "Samir Janveja",
        "title": "VP of Strategic Accounts",
        "experience_years": 14,
        "location": "Remote",
        "education": "MBA",
        "notice_period": "30 days",
        "salary_expectation": "50 LPA",
        "preferred_work_mode": "Remote",
        "current_job_satisfaction": "High",
        "summary": "Managing key strategic partnerships and enterprise accounts.",
        "skills": ["Enterprise Sales", "Strategic Partnerships", "Negotiation", "Business Development"],
        "past_roles": [],
        "certifications": []
    },
    {
        "id": "c_05",
        "name": "Purva Bhandari",
        "title": "Head of Strategy",
        "experience_years": 10,
        "location": "Remote",
        "education": "MBA",
        "notice_period": "45 days",
        "salary_expectation": "40 LPA",
        "preferred_work_mode": "Hybrid",
        "current_job_satisfaction": "High",
        "summary": "Defining the roadmap and strategic initiatives for scaling AI products.",
        "skills": ["Corporate Strategy", "Product Strategy", "Market Analysis", "Leadership"],
        "past_roles": [],
        "certifications": []
    },
    {
        "id": "c_06",
        "name": "Mahesh Reddy",
        "title": "Engineering Lead",
        "experience_years": 9,
        "location": "Hyderabad, India",
        "education": "B.Tech Computer Science",
        "notice_period": "60 days",
        "salary_expectation": "35 LPA",
        "preferred_work_mode": "Hybrid",
        "current_job_satisfaction": "High",
        "summary": "Engineering lead overseeing full-stack development and backend architecture.",
        "skills": ["System Design", "Backend Architecture", "Python", "Go", "Cloud Computing", "Team Leadership"],
        "past_roles": [],
        "certifications": []
    },
    {
        "id": "c_07",
        "name": "Amanda Brackbill",
        "title": "Customer Success Lead",
        "experience_years": 7,
        "location": "Remote",
        "education": "B.A. Communications",
        "notice_period": "30 days",
        "salary_expectation": "20 LPA",
        "preferred_work_mode": "Remote",
        "current_job_satisfaction": "High",
        "summary": "Ensuring enterprise clients achieve maximum value from AI integrations.",
        "skills": ["Customer Success", "Client Onboarding", "CRM", "Retention Strategy"],
        "past_roles": [],
        "certifications": []
    },
    {
        "id": "c_08",
        "name": "Sajo Mathews",
        "title": "Agentic AI Specialist",
        "experience_years": 6,
        "location": "Remote",
        "education": "M.Tech Artificial Intelligence",
        "notice_period": "30 days",
        "salary_expectation": "28 LPA",
        "preferred_work_mode": "Remote",
        "current_job_satisfaction": "High",
        "summary": "Specialist in building multi-agent workflows and autonomous systems.",
        "skills": ["LangChain", "LangGraph", "LLMs", "Python", "Agentic Workflows"],
        "past_roles": [],
        "certifications": []
    },
    {
        "id": "c_09",
        "name": "Tanmay Asthana",
        "title": "Machine Learning Engineer",
        "experience_years": 4,
        "location": "Hyderabad, India",
        "education": "B.Tech Computer Science",
        "notice_period": "30 days",
        "salary_expectation": "22 LPA",
        "preferred_work_mode": "Hybrid",
        "current_job_satisfaction": "High",
        "summary": "Focused on deploying ML models and building scalable inference pipelines.",
        "skills": ["Machine Learning", "MLOps", "Python", "Docker", "AWS", "TensorFlow"],
        "past_roles": [],
        "certifications": []
    },
    {
        "id": "c_10",
        "name": "Jaiprasad Reddy",
        "title": "ML Lead - Post-training, RLHF, LLM",
        "experience_years": 8,
        "location": "Hyderabad, India",
        "education": "M.S. Data Science",
        "notice_period": "45 days",
        "salary_expectation": "42 LPA",
        "preferred_work_mode": "Hybrid",
        "current_job_satisfaction": "High",
        "summary": "Leading the fine-tuning, RLHF, and post-training optimization of large language models.",
        "skills": ["LLM Fine-tuning", "RLHF", "PyTorch", "HuggingFace", "Distributed Training", "NLP"],
        "past_roles": [],
        "certifications": []
    },
    {
        "id": "c_11",
        "name": "Shatakshi",
        "title": "HR Director",
        "experience_years": 10,
        "location": "Hyderabad, India",
        "education": "MBA HR",
        "notice_period": "30 days",
        "salary_expectation": "30 LPA",
        "preferred_work_mode": "Hybrid",
        "current_job_satisfaction": "High",
        "summary": "Scaling the team and building a strong engineering culture at Deccan AI.",
        "skills": ["Talent Acquisition", "Employee Engagement", "HR Strategy", "Operations"],
        "past_roles": [],
        "certifications": []
    },
    {
        "id": "c_12",
        "name": "Siddhi",
        "title": "Senior DevOps Engineer",
        "experience_years": 5,
        "location": "Remote",
        "education": "B.Tech IT",
        "notice_period": "30 days",
        "salary_expectation": "24 LPA",
        "preferred_work_mode": "Remote",
        "current_job_satisfaction": "High",
        "summary": "Automating deployments and ensuring high availability across cloud environments.",
        "skills": ["Kubernetes", "Docker", "Terraform", "CI/CD", "AWS"],
        "past_roles": [],
        "certifications": []
    },
    {
        "id": "c_13",
        "name": "Bhavya",
        "title": "Frontend Engineer",
        "experience_years": 3,
        "location": "Remote",
        "education": "B.Tech Computer Science",
        "notice_period": "30 days",
        "salary_expectation": "14 LPA",
        "preferred_work_mode": "Remote",
        "current_job_satisfaction": "High",
        "summary": "Crafting beautiful and responsive user interfaces.",
        "skills": ["React", "TypeScript", "Tailwind CSS", "Next.js"],
        "past_roles": [],
        "certifications": []
    },
    {
        "id": "c_14",
        "name": "Rituraj Sarkar",
        "title": "Senior Data Engineer",
        "experience_years": 6,
        "location": "Remote",
        "education": "B.Tech Computer Science",
        "notice_period": "45 days",
        "salary_expectation": "26 LPA",
        "preferred_work_mode": "Remote",
        "current_job_satisfaction": "High",
        "summary": "Building scalable data pipelines for LLM training datasets.",
        "skills": ["Apache Spark", "Python", "SQL", "Airflow", "Kafka"],
        "past_roles": [],
        "certifications": []
    },
    {
        "id": "c_15",
        "name": "Aakash Ukande",
        "title": "Backend Engineer",
        "experience_years": 4,
        "location": "Remote",
        "education": "B.Tech IT",
        "notice_period": "30 days",
        "salary_expectation": "18 LPA",
        "preferred_work_mode": "Remote",
        "current_job_satisfaction": "High",
        "summary": "Developing robust APIs for AI applications.",
        "skills": ["Python", "FastAPI", "PostgreSQL", "Redis", "Docker"],
        "past_roles": [],
        "certifications": []
    },
    {
        "id": "c_16",
        "name": "Satyam Dashora",
        "title": "Junior ML Engineer",
        "experience_years": 1,
        "location": "Remote",
        "education": "B.Tech Artificial Intelligence",
        "notice_period": "15 days",
        "salary_expectation": "8 LPA",
        "preferred_work_mode": "Remote",
        "current_job_satisfaction": "High",
        "summary": "Assisting with data preparation and model evaluation.",
        "skills": ["Python", "Pandas", "Scikit-learn", "Jupyter"],
        "past_roles": [],
        "certifications": []
    },
    {
        "id": "c_17",
        "name": "Shruti Vinod Nair",
        "title": "Mid-Level Data Scientist",
        "experience_years": 3,
        "location": "Remote",
        "education": "M.Sc Data Science",
        "notice_period": "30 days",
        "salary_expectation": "15 LPA",
        "preferred_work_mode": "Remote",
        "current_job_satisfaction": "High",
        "summary": "Analyzing data and training predictive models.",
        "skills": ["Machine Learning", "Python", "SQL", "Data Visualization"],
        "past_roles": [],
        "certifications": []
    },
    {
        "id": "c_18",
        "name": "Anshool Agarwal",
        "title": "Senior Backend Developer",
        "experience_years": 5,
        "location": "Remote",
        "education": "B.Tech Computer Science",
        "notice_period": "30 days",
        "salary_expectation": "25 LPA",
        "preferred_work_mode": "Remote",
        "current_job_satisfaction": "High",
        "summary": "Designing high-throughput microservices.",
        "skills": ["Go", "Python", "Microservices", "System Design"],
        "past_roles": [],
        "certifications": []
    },
    {
        "id": "c_19",
        "name": "Challa Vijay Sarma",
        "title": "Cloud Architect",
        "experience_years": 7,
        "location": "Remote",
        "education": "B.Tech ECE",
        "notice_period": "45 days",
        "salary_expectation": "32 LPA",
        "preferred_work_mode": "Remote",
        "current_job_satisfaction": "High",
        "summary": "Managing cloud infrastructure and security for AI deployments.",
        "skills": ["AWS", "GCP", "Cloud Security", "Infrastructure as Code"],
        "past_roles": [],
        "certifications": []
    },
    {
        "id": "c_20",
        "name": "Shreta Singh",
        "title": "QA Automation Engineer",
        "experience_years": 4,
        "location": "Remote",
        "education": "B.Tech IT",
        "notice_period": "30 days",
        "salary_expectation": "16 LPA",
        "preferred_work_mode": "Remote",
        "current_job_satisfaction": "High",
        "summary": "Ensuring the reliability of AI applications through automated testing.",
        "skills": ["Selenium", "PyTest", "CI/CD", "Quality Assurance"],
        "past_roles": [],
        "certifications": []
    },
    {
        "id": "c_21",
        "name": "Fawaz Sharief",
        "title": "Product Designer",
        "experience_years": 4,
        "location": "Remote",
        "education": "B.Des",
        "notice_period": "30 days",
        "salary_expectation": "18 LPA",
        "preferred_work_mode": "Remote",
        "current_job_satisfaction": "High",
        "summary": "Designing intuitive interfaces for complex AI tools.",
        "skills": ["Figma", "UI/UX", "User Research", "Prototyping"],
        "past_roles": [],
        "certifications": []
    },
    {
        "id": "c_22",
        "name": "Padhmapriya Nagarajan",
        "title": "Full Stack Engineer",
        "experience_years": 5,
        "location": "Remote",
        "education": "B.Tech Computer Science",
        "notice_period": "30 days",
        "salary_expectation": "22 LPA",
        "preferred_work_mode": "Remote",
        "current_job_satisfaction": "High",
        "summary": "Developing end-to-end features for internal dashboards.",
        "skills": ["React", "Node.js", "Express", "MongoDB", "TypeScript"],
        "past_roles": [],
        "certifications": []
    },
    {
        "id": "c_23",
        "name": "Manideep Vaddi",
        "title": "Security Engineer",
        "experience_years": 4,
        "location": "Remote",
        "education": "B.Tech Cyber Security",
        "notice_period": "30 days",
        "salary_expectation": "20 LPA",
        "preferred_work_mode": "Remote",
        "current_job_satisfaction": "High",
        "summary": "Securing infrastructure and AI endpoints.",
        "skills": ["Cyber Security", "Penetration Testing", "Network Security", "Python"],
        "past_roles": [],
        "certifications": []
    },
    {
        "id": "c_24",
        "name": "Indrayudh Mandal",
        "title": "Research Scientist",
        "experience_years": 3,
        "location": "Remote",
        "education": "M.S. Computer Science",
        "notice_period": "30 days",
        "salary_expectation": "25 LPA",
        "preferred_work_mode": "Remote",
        "current_job_satisfaction": "High",
        "summary": "Researching novel architectures for foundation models.",
        "skills": ["Research", "Deep Learning", "Mathematics", "PyTorch"],
        "past_roles": [],
        "certifications": []
    },
    {
        "id": "c_25",
        "name": "Rohan Desai",
        "title": "Technical Writer",
        "experience_years": 3,
        "location": "Remote",
        "education": "B.A. English",
        "notice_period": "30 days",
        "salary_expectation": "12 LPA",
        "preferred_work_mode": "Remote",
        "current_job_satisfaction": "Moderate",
        "summary": "Writing comprehensive documentation for APIs and AI models.",
        "skills": ["Technical Writing", "Documentation", "Markdown", "API Specs"],
        "past_roles": [],
        "certifications": []
    },
    {
        "id": "c_26",
        "name": "Kavya Patel",
        "title": "Junior Frontend Developer",
        "experience_years": 1,
        "location": "Remote",
        "education": "B.Tech IT",
        "notice_period": "15 days",
        "salary_expectation": "8 LPA",
        "preferred_work_mode": "Remote",
        "current_job_satisfaction": "Moderate",
        "summary": "Assisting with UI components and bug fixes.",
        "skills": ["HTML", "CSS", "JavaScript", "React"],
        "past_roles": [],
        "certifications": []
    },
    {
        "id": "c_27",
        "name": "Rahul Sharma",
        "title": "Data Analyst",
        "experience_years": 2,
        "location": "Remote",
        "education": "B.Sc Mathematics",
        "notice_period": "15 days",
        "salary_expectation": "10 LPA",
        "preferred_work_mode": "Remote",
        "current_job_satisfaction": "Moderate",
        "summary": "Creating dashboards and analyzing user metrics.",
        "skills": ["SQL", "Tableau", "Excel", "Data Analysis"],
        "past_roles": [],
        "certifications": []
    },
    {
        "id": "c_28",
        "name": "Neha Gupta",
        "title": "Scrum Master",
        "experience_years": 5,
        "location": "Remote",
        "education": "B.Tech",
        "notice_period": "30 days",
        "salary_expectation": "18 LPA",
        "preferred_work_mode": "Remote",
        "current_job_satisfaction": "High",
        "summary": "Facilitating agile ceremonies for engineering teams.",
        "skills": ["Agile", "Scrum", "Jira", "Project Management"],
        "past_roles": [],
        "certifications": []
    },
    {
        "id": "c_29",
        "name": "Amit Kumar",
        "title": "SRE",
        "experience_years": 4,
        "location": "Remote",
        "education": "B.Tech Computer Science",
        "notice_period": "30 days",
        "salary_expectation": "20 LPA",
        "preferred_work_mode": "Remote",
        "current_job_satisfaction": "Moderate",
        "summary": "Monitoring systems and handling incidents.",
        "skills": ["Linux", "Python", "Monitoring", "Incident Response"],
        "past_roles": [],
        "certifications": []
    },
    {
        "id": "c_30",
        "name": "Priya Singh",
        "title": "AI Ethics Researcher",
        "experience_years": 2,
        "location": "Remote",
        "education": "M.A. Philosophy",
        "notice_period": "30 days",
        "salary_expectation": "14 LPA",
        "preferred_work_mode": "Remote",
        "current_job_satisfaction": "High",
        "summary": "Researching bias and ethical implications in LLMs.",
        "skills": ["AI Ethics", "Research", "Policy", "Documentation"],
        "past_roles": [],
        "certifications": []
    }
]

file_path = "c:/Users/HP/Desktop/deccan-catalyst-scout/data/candidates.json"
os.makedirs(os.path.dirname(file_path), exist_ok=True)
with open(file_path, "w") as f:
    json.dump(candidates, f, indent=4)

print(f"Successfully generated {len(candidates)} candidates.")
